language: go

os:
  - linux

sudo: false
dist: bionic
go: 1.13.x

notifications:
  email: false

script:
  - make build
  - make build-linux
  - make check-cmdref
  - make check-crdgen
  - make unit-tests
